### ISSUE TITLE
Not able to access setting page.

### ISSUE THREAD

**Issue by mxmkmarquette** [JoeSz/Exopite-SEO-Core#1]
i'm not able to access the setting page, it redirect me to the home page.

**Comment by JoeSz** [comment]
since when? 

Yesterday I did change things because of the gzip detection. The API site is down, cause error. This was yesterday fixed. Do you have the newest version?

**Comment by mxmkmarquette** [comment]
Hi i have this problem since a 2 version don't know why when i hit the button on the extension part of wordpress it redirect me to the homepage of my wordpress not even in wp-admin at the homepage of my website.

**Comment by JoeSz** [comment]
I'm not sure, what do you mind by version 2. Current version is 20181123. Your error tells me, your javascrit is not loaded. Please check in the development tool -> console.

**Comment by mxmkmarquette** [comment]
i do not see any error in the console thats why its weird

**Comment by JoeSz** [comment]
Which version do you use?

**Comment by mxmkmarquette** [comment]
20181123 the last one you push

**Comment by JoeSz** [comment]
Strage. Did you tried it with all (other) plugins off and twentynine wordpress theme?

**Comment by JoeSz** [comment]
Can you please also copy your settings here? (Maybe I see more then)

**Comment by JoeSz** [comment]
I will close this because of the lack of information.
